language: ruby
cache: bundler

branches:
    only:
        - master

before_install:
    - gem install bundler
    - nvm install
    - npm ci

script: bundle exec rake test

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
