language: ruby

branches:
  only:
    - master

before_install: 
    - nvm install 8
    - npm install

script: bundle exec rake test 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
